### ISSUE TITLE
AttributeError: 'CustomDataLoader' object has no attribute 'cond_bbox_prefix'

### ISSUE THREAD

**Issue by necroshine0** [ProjectNUWA/LayoutNUWA#9]
I have tried to run the model on datasets provided and faced the problem of attribute error: in `build_code.py`, [there is](https://github.com/ProjectNUWA/LayoutNUWA/blob/main/convertHTML/build_code.py#L402)  accessing to the `CustomDataloader` class attribute `self.cond_bbox_prefix` which has never been initialized anywhere before.
Hence, as one tries to run the following command:
```
python convertHTML/build_code.py \
    --model_path_or_name meta-llama/Llama-2-7b-hf \
    --dataset_name publaynet \
    --dataset_path data/publaynet-max25 \
    --save_path data/publaynet-max25/html_format \
    --bbox_quantization code \
    --consistency_num 10 \
    --add_task_instruction
```
he will get an attribute error:
```
Traceback (most recent call last):
  File "C:\Users\Name\layout-nuwa\convertHTML\build_code.py", line 646, in <module>
    if args.consistency_num > 1:
  File "C:\Users\Name\layout-nuwa\convertHTML\build_code.py", line 558, in __iter__
  File "C:\Users\Name\layout-nuwa\convertHTML\build_code.py", line 401, in custom_function
    self.cond_bbox_prefix.format(categories=cate, bbox_html=bbox_html)
  File "C:\Users\Name\layout-nuwa\convertHTML\build_code.py", line 402, in <listcomp>
    for cate, bbox_html in zip(batched_cond_cate, batched_cond_bbox)
AttributeError: 'CustomDataLoader' object has no attribute 'cond_bbox_prefix'
```
Running in Windows 10, no DeepSpeed args are using.

**Comment by necroshine0** [comment]
[Answer](https://github.com/ProjectNUWA/LayoutNUWA/issues/2) is found
